### ISSUE TITLE
GUID should contain 32 digits.......

### ISSUE THREAD

**Issue by michouser** [UretzkyZvi/Monitor-Applications-Using-SQL-Queries#10]
I am getting the error when trying to use the MP.  This is the error I am currently seeing.

![image](https://user-images.githubusercontent.com/32964002/32325902-38835eae-bfa7-11e7-81a4-0689a850fab5.png)

**Comment by UretzkyZvi** [comment]
Hi,
do u use the latest version 2.1.0.5?
I am familiar with this problem in the previous version.

**Comment by UretzkyZvi** [comment]
try the new version
[QueryOleDbMonitorLibrary.mp](https://github.com/UretzkyZvi/Monitor-Applications-Using-SQL-Queries/raw/master/ManagementPacks/QueryOleDbMonitorLibrary.mp)
[QueryOleDbMonitorTemplate.mpb](https://github.com/UretzkyZvi/Monitor-Applications-Using-SQL-Queries/raw/master/ManagementPacks/QueryOleDbMonitorTemplate.mpb)
thanks
