### ISSUE TITLE
An OLE DB Provider was not specified........

### ISSUE THREAD

**Issue by michouser** [UretzkyZvi/Monitor-Applications-Using-SQL-Queries#11]
See image of error message below.

![image](https://user-images.githubusercontent.com/32964002/32326681-1f1e5768-bfaa-11e7-8925-0591e71b56b6.png)

**Comment by UretzkyZvi** [comment]
do u use the latest version 2.1.0.5?

**Comment by michouser** [comment]
I am currently using the version 2.0.0.5

I was unable to download the latest version.

Could you provide a link?

**Comment by michouser** [comment]
I downloaded again and the version is the same as what I have currently installed.

Version 2.0.0.5 for QueryOleDbMonitorTemplate

**Comment by UretzkyZvi** [comment]
I am on it

**Comment by UretzkyZvi** [comment]
please try again
[QueryOleDbMonitorTemplate.mpb](https://github.com/UretzkyZvi/Monitor-Applications-Using-SQL-Queries/raw/master/ManagementPacks/QueryOleDbMonitorTemplate.mpb)

[QueryOleDbMonitorLibrary.mp](https://github.com/UretzkyZvi/Monitor-Applications-Using-SQL-Queries/raw/master/ManagementPacks/QueryOleDbMonitorLibrary.mp)

**Comment by UretzkyZvi** [comment]
The MPs should solve your problem, although, I found a new bug I will update the MPs today.. sorry for all the bugs.. I am sure that final version will worth the effort :wink:

**Comment by michouser** [comment]
Ok, great.  Cannot wait for the opportunity to use said MP.

Could you let me know when it is available for download?  It would be greatly appreciated.

**Comment by michouser** [comment]
Imported the correct version of template but the new version of library failed.

Template ver 2.1.0.5
Library ver 1.0.0.1

**Comment by UretzkyZvi** [comment]
I have done some changes.
Sorry but you would not to delete the current MPs in your SCOM environment and import new MPs
version 2.1.0.8 to keep it more easy to maintain I change library mp to version 2.1.0.8

[QueryOleDbMonitorTemplate.mpb](https://github.com/UretzkyZvi/Monitor-Applications-Using-SQL-Queries/raw/master/ManagementPacks/QueryOleDbMonitorTemplate.mpb)

[QueryOleDbMonitorLibrary.mp)](https://github.com/UretzkyZvi/Monitor-Applications-Using-SQL-Queries/raw/master/ManagementPacks/QueryOleDbMonitorLibrary.mp)
