### ISSUE TITLE
Custom Alert Descriptions and Names

### ISSUE THREAD

**Issue by snazy2000** [UretzkyZvi/Monitor-Applications-Using-SQL-Queries#13]
Would be nice to be able to change the Alert Description and Alert Name against each rule

This can be done by going to the Monitor but it seems to get overridden if you change any settings?

**Comment by UretzkyZvi** [comment]
I will do that in the next version, meanwhile, I add a query name in alert name, 
v2.2.0.0 
I fixed the issue with the monitor not change state

[QueryOleDbMonitorLibrary.mp](https://github.com/UretzkyZvi/Monitor-Applications-Using-SQL-Queries/raw/master/ManagementPacks/QueryOleDbMonitorLibrary.mp)
[QueryOleDbMonitorTemplate.mpb](https://github.com/UretzkyZvi/Monitor-Applications-Using-SQL-Queries/raw/master/ManagementPacks/QueryOleDbMonitorTemplate.mpb)

**Comment by snazy2000** [comment]
Ok thanks this is a big one for me as well as being able to set the alert type warning or critical

In our environment we do not need / want the full description you put and same with the name hopefully we can do this soon :) thanks again for amazing MP

**Comment by UretzkyZvi** [comment]
Thanks you :relaxed:

**Comment by michouser** [comment]
Uretzky,

The link about to the v2.2.2.0 version of the MP is not working, could you provide a new link or send the files direct?

Mike

**Comment by UretzkyZvi** [comment]
[Management Packs](https://github.com/UretzkyZvi/Monitor-Applications-Using-SQL-Queries/tree/master/ManagementPacks)

**Comment by michouser** [comment]
Zvi,

I am unable to download from github for some reason.

-Mike

**Comment by UretzkyZvi** [comment]
Hi Mike,

Have you tried those steps?

![capture1](https://user-images.githubusercontent.com/6106808/33959542-850681e2-e050-11e7-91b5-f92b15659aa8.PNG)
![capture2](https://user-images.githubusercontent.com/6106808/33959543-8534be0e-e050-11e7-85d1-209552de179c.PNG)
![capture3](https://user-images.githubusercontent.com/6106808/33959544-858922c8-e050-11e7-94f7-b4674374ddf0.PNG)

**Comment by michouser** [comment]
Zvi,

My outlook ripped the images out and I was unable to get to the links.

**Comment by michouser** [comment]
Zvi,

I was finally able to download the files.

Thank you again.  Cannot wait to do some testing.

-Mike

**Comment by michouser** [comment]
Zvi,

As of right now, prior to v2.2.0.0 I was able to see an object that was not being monitored.  Now I am not seeing any objects that have been built.

Before the upgrade the query test worked in providing me a result, now I am getting the following error.

-Mike

[cid:image001.png@01D37964.BCA53330]

**Comment by UretzkyZvi** [comment]
@michouser hi,
Could you resend the screenshot.
Anyway, the difference between previous and current version is that in a previous version test button executed with current user credentials that you open the SCOM console and in a new version the test execute a SCOM task that run with SCOM default credentials.
Thanks

**Comment by michouser** [comment]
Zvi,

The error that I am getting is the following.

-Mike

Error before update
[cid:image001.png@01D3799E.8D793180]

Error after update
[cid:image002.png@01D3799E.8D793180]

**Comment by UretzkyZvi** [comment]
Hi,
I did not receive your screenshots. 
Please try to resend them.
Thanks,

**Comment by michouser** [comment]
Zvi,
Here is the error when I try to run the test from within the monitor under the authoring view.  This monitor was created before the latest upgrade.
![capture](https://user-images.githubusercontent.com/32964002/34685077-1448fa94-f49f-11e7-9051-7924ccb4e746.JPG)

This is the error I am receiving after the latest upgrade.  This monitor was created after the latest upgrade.

![capture](https://user-images.githubusercontent.com/32964002/34685175-7106bf50-f49f-11e7-9f93-01c473a105a7.JPG)

Let me know if you can do a remote debug.  I am willing to do that.

Mike

**Comment by UretzkyZvi** [comment]
Hi Mike, 
The error point an error in your SQL query. Can you share the query?. I will try to find the error.

**Comment by UretzkyZvi** [comment]
Hi Mike, 
The error point an error in your SQL query. Can you share the query?. I will try to find the error.

**Comment by UretzkyZvi** [comment]
Hi Mike, 
The error point an error in your SQL query. Can you share the query?. I will try to find the error.

**Comment by UretzkyZvi** [comment]
Hi Mike, 
The error point an error in your SQL query. Can you share the query?. I will try to find the error.

**Comment by UretzkyZvi** [comment]
Hi Mike, 
The error point an error in your SQL query. Can you share the query?. I will try to find the error.

**Comment by UretzkyZvi** [comment]
Hi Mike, 
The error point an error in your SQL query. Can you share the query?. I will try
 to find the error.

**Comment by UretzkyZvi** [comment]
Hi Mike, 
The error point an error in your SQL query. Can you share the query?. I will try
 to find the error.

**Comment by michouser** [comment]
Zvi,

Here is the query.  It should be the same for each monitor even though I am seeing a different error message.

-Mike

SELECT count(*) FROM [Captiva].[dbo].[Tbl_Batches] where [BTStatus]!=17 and BTPriority!=0 and datediff(minute,BTCreationDttm,getutcdate())&amp;gt; 15

**Comment by UretzkyZvi** [comment]
please try to execute this query :
SELECT count(*) FROM [Captiva].[dbo].[Tbl_Batches] where [BTStatus]!=17 and BTPriority!=0 and datediff(minute,BTCreationDttm,getutcdate()) > 15

I changed the characters "&amp;gt;" to greater than ">"

**Comment by michouser** [comment]
Zvi,

Ok, the test has worked, but for some reason the indicator is still indicating not monitored.  Thoughts?

-Mike

**Comment by UretzkyZvi** [comment]
Hi,
Before, we will go more in-depth investigation. Please check that the agent proxy is enabled.

**Comment by michouser** [comment]
Zvi

Currently I have a MP that ensures that the aspect is configured on every server.

The Query DB Monitoring is hitting a SQL cluster right now, but the two servers that make up the cluster the functionality you indicate below is configured.

-Mike

**Comment by UretzkyZvi** [comment]
Okay,
If it possible, I can assist you remotely.
Would you like me to assist you remotely?

**Comment by michouser** [comment]
Zvi,

Yes, that would be great.

-Mike

**Comment by UretzkyZvi** [comment]
Hi, my email address is uretsky.zvi@gmail.com
Let's try to schedule a meeting, send me your optional dates

**Comment by snazy2000** [comment]
Any update on this one it appears to have been closed?

Looks like the issue got off track from what was raised :(

**Comment by UretzkyZvi** [comment]
Sorry, I will check that.
Meanwhile, you can open the MP XML and change the alert name manually

**Comment by snazy2000** [comment]
I want to be able to set it against each alert and also change the alert type warning / error.

Current I can go in to the monitor and change it in there but if query is edited then it all gets reset :(

**Comment by UretzkyZvi** [comment]
Done 👍  Check https://www.savision.com/free-management-packs/
