### ISSUE TITLE
Query is not exactly the same in edit mode

### ISSUE THREAD

**Issue by snazy2000** [UretzkyZvi/Monitor-Applications-Using-SQL-Queries#15]
![image](https://user-images.githubusercontent.com/1378836/32448900-130c0428-c308-11e7-9a59-d6f36811e8b5.png)

Should be > not &gt;

**Comment by UretzkyZvi** [comment]
It is ok, 
![image](https://user-images.githubusercontent.com/6106808/32451864-a9bbc030-c320-11e7-920a-6e2cea920e11.png)
and when I open this monitor as a template
![image](https://user-images.githubusercontent.com/6106808/32451982-ee142d1c-c320-11e7-8218-1074bcde6e51.png)

Do you have any monitoring problems?

**Comment by snazy2000** [comment]
I have been correcting it every time in case it broke stuff
