### ISSUE TITLE
Option for a warning state (3-state monitor)

### ISSUE THREAD

**Issue by Jeffrey-schilt** [UretzkyZvi/Monitor-Applications-Using-SQL-Queries#16]
Hi!

First of all, thanks for this great piece of work. Much appreciated!

May i suggest to create a possibility for a 3-state monitor? In some cases, the result of the SQL query is not Always healthy or critical in our case. An extra warning state would be great!

Thanks for your consideration!

**Comment by UretzkyZvi** [comment]
Hi, 
Ok I'll work on it

**Comment by Robert-Poole** [comment]
I also need a 3 state monitor, is there any update on this?

Thanks in advance

Rob

**Comment by UretzkyZvi** [comment]
Done :) Check https://www.savision.com/free-management-packs/
