### ISSUE TITLE
Other providers?

### ISSUE THREAD

**Issue by miau101** [UretzkyZvi/Monitor-Applications-Using-SQL-Queries#18]
Hi Zvi,
My compliments for this fantastic mp! Would it be possible to make use of other OleDB providers like Oracle and edit this in the xml?
Kind regards,
Michiel

**Comment by UretzkyZvi** [comment]
Hi Michiel,
Microsoft does not provide a management pack for Oracle instead there are several 3rd party vendors. Therefore, it will be difficult for maintain.
However, you are welcome to clone the project and add the necessary code, if you need with that I will happy to help ;-)
