### ISSUE TITLE
SCOM 2016 with SQL 2016 MPs?

### ISSUE THREAD

**Issue by Ryan2065** [UretzkyZvi/Monitor-Applications-Using-SQL-Queries#19]
Does this work on SCOM 2016? 

We upgraded our test environment recently and are having problems with this management pack. When I try to create a new query monitor from the authoring page selecting OleDB Query Monitoring, we cannot get past the page "Connection And Query Settings". When we click Browse under Database Engine, then Search, the error pops up with "Object reference not set to an instance of an object".  Here's the error:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EnterpriseManagement.Mom.Internal.UI.MPImageCache.GetImage(ManagementPackElement element, Guid category, Guid& imageId)
   at Microsoft.EnterpriseManagement.Mom.Internal.UI.MPImageCache.GetImage(ManagementPackElement element, Guid category)
   at Microsoft.EnterpriseManagement.Mom.Internal.UI.Common.ComponentMethodLibrary.GetImageFromSharedCache(ManagementPackClass entity, IComponent component)
   at ManageQueryOleDbMonitorUI.DBEnginePickerControl.PopulateDBEngines()
   at ManageQueryOleDbMonitorUI.DBEnginePickerControl.Search(CancelFlagWrapper cancelFlag)
   at Microsoft.EnterpriseManagement.Mom.Internal.UI.AsyncChooserDialogItemProvider.SearchAsyncBegin(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

Our troubleshooting:
Clear Management Server cache
Clear console cache
Re-import management pack

So, does this MP work with SCOM 2016 and the SQL 2016 MPs? We don't have any other SQL MPs installed, does this Database Engine picker search for something that's only created with the older MPs? At a loss on how to fix this and it's holding up our upgrade.

To end on a better note, this is holding up our upgrade because the MP is great and we love it. Some direction on how to troubleshoot this would be greatly appreciated!

Thank you!

**Comment by UretzkyZvi** [comment]
Hi,
Good question, I don't know. 
I don't have a SCOM 2016 environment yet. Also, I have checked the code behind and I don't find a good reason why it throw a null object error.
If it possible and you agree, I can assist you remotely to debug

**Comment by Ryan2065** [comment]
I'd love to have you assist remotely but would not be able to due to security protocols. I'll check with some others in the community who have SCOM 2016 and see if they can use this MP.

**Comment by UretzkyZvi** [comment]
Okay, let me know if you need any help.

**Comment by UretzkyZvi** [comment]
Hi,
I will upgrade my environment next week, and I wonder if you solved the problem?

**Comment by michouser** [comment]
Zvi,

Nope, have not solved the problem.

We need to exchange email addresses.

-Mike

**Comment by Pat6332** [comment]
Hey Zvi,

I also just attempted to run this in my SCOM 2016 UR4 environment and am seeing the same issue as Ryan.  We are running this MP in our 2012R2 environment and we love it!!! I'd really like to pull this into our 2016 environment....so much potential.

**Comment by Pat6332** [comment]
Just wanted to leave a quick follow up / workaround for the issue.  If we export the management packs from our SCOM 2012 environment and import them into SCOM 2016 environment, everything works great.  So it looks like its the Wizard itself that is having the issue.

**Comment by UretzkyZvi** [comment]
@Pat6332 thank you; I will fix this problem.

**Comment by UretzkyZvi** [comment]
Short update:
I tried the MP in SCOM 2016 RTM version, and it works.
I will upgrade to UR 4 and let you know if it still works.

**Comment by kkubalsky** [comment]
Can someone please make available a version of this package exported from SCOM 2012?  We are running into the same issues as Pat6332 trying to run this in SCOM 2016 but do not have access to a 2012 environment.

**Comment by UretzkyZvi** [comment]
Please make sure you have all required MPs installed on the SCOM 2016 environment.
Required MPs:
1. Microsoft.SQLServer.Library.
2. Microsoft.SQLServer.2014.Discovery
3. Microsoft.SQLServer.2016.Discovery

**Comment by kkubalsky** [comment]
Thank you so much for the quick reply.  I am almost able to create a monitor but am now getting this error when I try to save:

[cid:59e073fd-311a-48c9-903c-5e5f15c3e3b2]

Any help you can provide would be greatly appreciated.

Best regards.

Kevin
________________________________

**Comment by UretzkyZvi** [comment]
I'm not familiar with this error, could you please add a screenshot of the error

**Comment by kkubalsky** [comment]
Thanks - I had a duplicate MP issue that i resolved.

Is there a way to target two Database engines with one monitor?

Best regards,
Kevin
________________________________

**Comment by UretzkyZvi** [comment]
Sorry, there is no way to target two DB with one monitor. 
However, if your company policy is allowed to create linking DB Server, then you can query two tables from different DB server. 
[Example of joining tables different servers ](http://www.mytecbits.com/microsoft/sql-server/joining-tables-different-servers)

**Comment by UretzkyZvi** [comment]
@kkubalsky , @Ryan2065, and @Pat6332 can I close the issue?

**Comment by Pat6332** [comment]
I'm good...close it


-------- Original message --------

**Comment by rodrigopenna** [comment]
I vahe the same issue. Trying to run this MP on SCOM 2019...
![image](https://user-images.githubusercontent.com/51041800/67043024-77dfe780-f0ff-11e9-9e1d-2009ed101d75.png)
