### ISSUE TITLE
State of the monitor stays as not monitored 

### ISSUE THREAD

**Issue by sakrayaami** [UretzkyZvi/Monitor-Applications-Using-SQL-Queries#20]
Hi,

Thank you for the great MP it will save a lot of trouble!
I've configured it and the test was successful however whenever I go to check the Group state or Just State in the Query Monitor folder it's in a state : Not monitored:
![capture](https://user-images.githubusercontent.com/37185333/37158201-bc001e54-22e2-11e8-9f58-d24f8d37974c.JPG)

**Comment by UretzkyZvi** [comment]
Hi, @sakrayaami  sorry for a late response, please make a sure that the agent proxy is enabled.

**Comment by sakrayaami** [comment]
Hi,

Agent proxy is enabled on the particular agent.

**Comment by UretzkyZvi** [comment]
Please verify that the query always return a numerical data. If you are not sure, send me the query I will try to help you.

**Comment by sakrayaami** [comment]
Hi,

The query gives always and only numerical data. Also the result is always in one line one column and it is between the numbers 10 and 50

**Comment by sakrayaami** [comment]
And just as a further clarification this is the query we use. I've change a bit of it for privacy purposes but in general whenever I run it in the test section it always outputs numeric value and the test is successful . 

``declare @start datetime, @end datetime
set @end = getdate()
set @start = DATEADD(minute,-10,@end)
select
	COUNT(distinct CallId) as Value
from DBname..ODR where start between @start and @end
    and Result in ('e')

**Comment by UretzkyZvi** [comment]
@sakrayaami hi,
It looks good.
Could you delete the monitor query, and create it again? If so, try it.

**Comment by sakrayaami** [comment]
I've created the whole thing couple of times and this didn't helped :(

**Comment by UretzkyZvi** [comment]
what is the management packs version you use?

**Comment by sakrayaami** [comment]
![capture](https://user-images.githubusercontent.com/37185333/37336257-c4379f92-26a8-11e8-84f0-efe29695b236.JPG)
2.2.0.1

**Comment by UretzkyZvi** [comment]
@sakrayaami, basically the module flow is running a query and then mapping a performance data, So, if query module return an empty data so the performance data mapping module will throw this unable to convert error.. therefore I think the problem is in the query module, so, since we know that the query is valid. maybe there is a permission issue. Please verify that that specific health service agent has the permission to execute this query

**Comment by sakrayaami** [comment]
Not so long ago we have implemented the following approach for monitoring the SQL servers:
https://blogs.technet.microsoft.com/kevinholman/2016/08/25/sql-mp-run-as-accounts-no-longer-required-2/
Maybe this is causing the issues, may I ask for you opinion?

**Comment by UretzkyZvi** [comment]
Sorry, I don't know.. you can check it out by giving the SCOM action account a permission to this database

**Comment by sakrayaami** [comment]
Hi again, 

Our SCOM action account has a sysadmin server role on the DB (sysadmin permissions). 
It is not mapped specifically to any DB however since it is a sysadmin on the SQL server it has permissions to do and go everywhere on the DB.
Any ideas?

**Comment by UretzkyZvi** [comment]
Try some a simple query like SELECT 2
just to eliminate an MP module bug.

**Comment by UretzkyZvi** [comment]
@sakrayaami hi,
I solved a similar problem by changing the Query type from string to richtext it means you can write more than 256 characters query. 
Please download and import this Managment Pack [MP v2.2.0.2](https://github.com/UretzkyZvi/Monitor-Applications-Using-SQL-Queries/blob/master/ManagementPacks/QueryOleDbMonitorLibrary.mp).

**Comment by sakrayaami** [comment]
Thank you for keep up this moving!
I've tried to update the MP and got this error:

QueryOleDbMonitorLibrary could not be imported.

If any management packs in the Import list are dependent on this management pack, the installation of the dependent management packs will fail.

Verification failed with 2 errors:
-------------------------------------------------------
Error 1:
Found error in 2|QueryOleDbMonitorLibrary/c7d1f91346117fc6|2.2.0.1|QueryOleDbMonitorLibrary|| with message:
Version 2.2.0.2 of the management pack is not upgrade compatible with older version 2.2.0.1. Compatibility check failed with 1 errors:

-------------------------------------------------------
Error 2:
Found error in 1|QueryOleDbMonitorLibrary/c7d1f91346117fc6|1.0.0.0|OleDBQueryMonitoring|| with message:
The property Type (Query) has a value that is not upgrade compatible. OldValue=string, NewValue=richtext.
-------------------------------------------------------

I will try to remove the old and install the updated.

**Comment by UretzkyZvi** [comment]
If you don't want to recreate previews queries, please follow these steps:
1. Export all current MPs that include all the queries. 
2. Delete exists MPs includeQueryOleDbMonitorLibrary.mp, and QueryOleDbMonitorTemplate.mpb.
3. Import fixed QueryOleDbMonitorLibrary.mp, and QueryOleDbMonitorTemplate.mpb
4. Open those MPs you exported in step 1 in notepad and change the version of QueryOleDbMonitorLibrary.mp, and
QueryOleDbMonitorTemplate.mpb in a reference section.
5. Import those MPs.

If you don't want to do all the changes you can follow the workaround, just rewrite the query as a stored procedure and execute it instead of the original query.

**Comment by sakrayaami** [comment]
Hi,

The very same error/issue is ongoing using a stored procedure. 
I've created a stored procedure with select 2 sql query, tested it in the configuration, it gave correct values however the very same situation is happening.
I am about to test it with SCOM 2016 now.

**Comment by UretzkyZvi** [comment]
Okay, I have another suggestion, try to trace the query using the SQL profiler, maybe you could figure out what is going on with the query

**Comment by UretzkyZvi** [comment]
@sakrayaami hi, did you solve the problem?

**Comment by sakrayaami** [comment]
It is very very funny and interesting how you have replied at the very same time as the issue has been resolved !
The problem came indeed from the Permissions.
Since we are using as I've mentioned above one MP that removes the need of Run As account, there was some kind of permission problem.
After removing the run as account from our SQL Run AS profile, everything went green and the alarms start working.
So thank you very much for the effort and time you've spend on this request, it was clearly my fault and not yours/management pack's .

**Comment by UretzkyZvi** [comment]
Thanks. Happy to hear that it works.
By the way, I opened a SCOM community chat in Gitter. You are welcome to join.
https://gitter.im/SCOM-Community/Lobby

**Comment by UretzkyZvi** [comment]
Fixed https://www.savision.com/free-management-packs/
