### ISSUE TITLE
Start and end time not honoured - SCOM 2016

### ISSUE THREAD

**Issue by greg-sharp** [UretzkyZvi/Monitor-Applications-Using-SQL-Queries#21]
Hi. Nice MP. Does exactly what I need. Thank you. However, the start and end times do not do what I would expect. Is the query monitor supposed to start and end in between those set times? If so, it does not seem to work with SCOM 2016 UR3 and SQL MP 7.0.0.0. The monitor just runs 24x7 on the interval (5 mins).  Am I missing something or could there be an issue?

**Comment by greg-sharp** [comment]
After flushing the management server and agent caches and resetting the status of monitors the issue is resolved.

**Comment by greg-sharp** [comment]
Sorry.  Had to reopen because the EndTime/EndDay seems to be an issue.

I discovered that an object state can change to Healthy before the StartTime but not to Critical.  This is fine as, in my case, a Critical state can carry over from a previous day and be be resolved the next morning.  

The Critical state will only be set if the test fails after the StartTime.  This is OK and is expected.

However, after the EndTime the state of the object can flipflop between Healthy and Critical which I did not expect and skews KPI reporting off the back of the monitor.

On further investigation it seems all monitors and discoveries created by the template persist my non-default EndTime but when editing the Scheduler Settings of the templated monitor the EndTime always defaults back to 23:59.  I have to change it from 23:59 before saving any other changes to retain the property value.

Am wondering if the failed retrieval of the changed EndTime config value in the editing window is happening on the agent meaning the StartTime is the only parameter being honoured?

**Comment by greg-sharp** [comment]
OK.  The plot thickens... the behaviour above is experienced when a sample rate of 1 is used.  Using 2 samples 'stabilises' the flip flopping object state.  I found that flushing the agent cache would also give random behaviours too.  So, I now use a sample rate of 2... and when the EndTime is reached the Health state reverts to Healthy if it was Critical, nice.

The Schedule window editor still always shows 23:59 for EndTime when setting a custom value though which is pain as you have to remember your EndTime if it's customised... that is likely a bug.

**Comment by UretzkyZvi** [comment]
Yes you are right this is a bug.. sorry for that I will fix it unfortunately I am working on this project when I have a free time and now it's a period that I don't have a lot of free time.. meanwhile please be aware of it and if you need to do some changes, don't forget to change the end time..

**Comment by sakrayaami** [comment]
Hi @UretzkyZvi 
Is there any updates on this?

**Comment by UretzkyZvi** [comment]
@sakrayaami sorry, I'm too busy now... anyway it is on my task list :-)

**Comment by UretzkyZvi** [comment]
Fixed 👍 check https://www.savision.com/free-management-packs/
