### ISSUE TITLE
Unable to import 2.2.0.2?

### ISSUE THREAD

**Issue by jannepn** [UretzkyZvi/Monitor-Applications-Using-SQL-Queries#22]
When trying to import the latest version (template 2.2.0.2 already imported) I get the following error:
QueryOleDbMonitorLibrary could not be imported.

If any management packs in the Import list are dependent on this management pack, the installation of the dependent management packs will fail.

Verification failed with 2 errors:
-------------------------------------------------------
Error 1:
Found error in 2|QueryOleDbMonitorLibrary/c7d1f91346117fc6|2.2.0.1|QueryOleDbMonitorLibrary|| with message:
Version 2.2.0.2 of the management pack is not upgrade compatible with older version 2.2.0.1. Compatibility check failed with 1 errors:

-------------------------------------------------------
Error 2:
Found error in 1|QueryOleDbMonitorLibrary/c7d1f91346117fc6|1.0.0.0|OleDBQueryMonitoring|| with message:
The property Type (Query) has a value that is not upgrade compatible. OldValue=string, NewValue=richtext.
-------------------------------------------------------

Do I have to remove and recreate all monitors when updating?

**Comment by UretzkyZvi** [comment]
If you don't want to recreate previews queries, please follow these steps:

Export all current MPs that include all the queries.
Delete exists MPs includeQueryOleDbMonitorLibrary.mp, and QueryOleDbMonitorTemplate.mpb.
Import fixed QueryOleDbMonitorLibrary.mp, and QueryOleDbMonitorTemplate.mpb
Open those MPs you exported in step 1 in notepad and change the version of QueryOleDbMonitorLibrary.mp, and
QueryOleDbMonitorTemplate.mpb in a reference section.
Import those MPs.

**Comment by jannepn** [comment]
I had to delete the management-pack were the queries were saved after exporting it since it had a reference to the QueryOledbmonitorMPs. But I guess that was implied in the Export all current MPs.
Thanks for the help.
