### ISSUE TITLE
Query not screened properly

### ISSUE THREAD

**Issue by bugriy** [UretzkyZvi/Monitor-Applications-Using-SQL-Queries#24]
If query contains symbols < or > it's replaced with &amp; &amp; &amp; &amp; gt or lt. There could me dozens of &amp; 

This query goes to SQL which causes fail. I tried to export xml and use CDATA but after I import MP, it's replaced with &amp;  again.

Workaround - not use < and > in queries, use BETWEEN operator instead and etc.

**Comment by UretzkyZvi** [comment]
Yes, I know this issue, I didn't get time to fix it yet. But I can suggest another workaround; you can wrap the query inside store procedure and execute it.

**Comment by UretzkyZvi** [comment]
Fixed :) https://www.savision.com/free-management-packs/
