### ISSUE TITLE
OleDB query monitoring in SCOM 1801

### ISSUE THREAD

**Issue by vijayhari80** [UretzkyZvi/Monitor-Applications-Using-SQL-Queries#26]
Hello,
I've imported oledb query monitoring MP in my SCOM environment. My requirement is generate an alerts for long running SQL queries on monitored SQL databases.
I tried to create query monitoring from Query oledb monitoring template and it couldn't pass the connectionand Query settings page. It says user  doen't have permission to perform the operation. How do i run the query monitoring under the service account which has access to all databases across the environment.

Please help me to fix this or guide me efficient way to achieve the long running queries monitoring in SCOM to get an alert and also configure the dashoboard.

Regards,
Vijay

**Comment by UretzkyZvi** [comment]
Hello Vijay, sorry for the late response. Do you still need help? The testing is done by using a SCOM console user credentials, so if you the default user account account has enough permissions the monitor will work. About the query you should ask for help from a DB administrator, he could write the correct query for you

**Comment by UretzkyZvi** [comment]
https://www.savision.com/free-management-packs/
