### ISSUE TITLE
Processing the template failed. See inner exception for details error

### ISSUE THREAD

**Issue by Robert-Poole** [UretzkyZvi/Monitor-Applications-Using-SQL-Queries#27]
Hi

When I try to create a query it fails with the message:

Date: 14/01/2019 10:39:16
Application: Operations Manager
Application Version: 7.3.13142.0
Severity: Error
Message: 

: Processing the template failed. See inner exception for details.
Verification failed with 2 errors:
-------------------------------------------------------
Error 1:
Found error in 1|Bridgewater.Management.Pack|1.0.0.0|QueryOleDbMonitorInitialDiscovery.0d8796374c574b0a8cfaf32272a5686f|| with message:
Failed to verify Discovery: QueryOleDbMonitorInitialDiscovery.0d8796374c574b0a8cfaf32272a5686f
: Cannot find ManagementPackElement [Type=ManagementPackClass, ID=Microsoft.Windows.Computer] in management pack ManagementPack:[Name=Microsoft.Windows.Server.2016.Discovery, KeyToken=31bf3856ad364e35, Version=10.0.21.0].

-------------------------------------------------------
Error 2:
Found error in 1|Bridgewater.Management.Pack|1.0.0.0|QueryOleDbMonitorInitialDiscovery.0d8796374c574b0a8cfaf32272a5686f/DS|| with message:
The configuration specified for Module DS is not valid.
: Cannot find specified MPElement Windows!Microsoft.Windows.Computer in expression: $MPElement[Name="Windows!Microsoft.Windows.Computer"]/PrincipalName$
Cannot find ManagementPackElement [Type=ManagementPackElement, ID=Microsoft.Windows.Computer] in management pack ManagementPack:[Name=Microsoft.Windows.Server.2016.Discovery, KeyToken=31bf3856ad364e35, Version=10.0.21.0].
-------------------------------------------------------
Failed to verify Discovery: QueryOleDbMonitorInitialDiscovery.0d8796374c574b0a8cfaf32272a5686fCannot find ManagementPackElement [Type=ManagementPackClass, ID=Microsoft.Windows.Computer] in management pack ManagementPack:[Name=Microsoft.Windows.Server.2016.Discovery, KeyToken=31bf3856ad364e35, Version=10.0.21.0].
: Verification failed with 2 errors:
-------------------------------------------------------

I've tried searching the forum for previous solutions but I cant find any that match. Are you able to help?

Thanks in advance.

Rob

**Comment by Robert-Poole** [comment]
Thanks for the reply, that works when I add it to a different management pack. Is there any way to get it working in the original mp or shall I leave it in a separate one?

BTW the management pack is great, thanks for taking the time to develop it.

Rob

**Comment by UretzkyZvi** [comment]
fixed https://www.savision.com/free-management-packs/
