### ISSUE TITLE
Cannot delete a 3 state monitor

### ISSUE THREAD

**Issue by Robert-Poole** [UretzkyZvi/Monitor-Applications-Using-SQL-Queries#29]
Hi

I'm trying to delete an unrequired monitor that I set up while testing but it just says:

Date: 09/10/2019 10:48:12
Application: Operations Manager
Application Version: 7.3.13142.0
Severity: Error
Message: The item you are trying to delete cannot be deleted because another object references it. The object must be deleted before this item can be deleted.

: Verification failed with 3 errors:
-------------------------------------------------------
Error 1:
Found error in 1|SQL.Monitoring|1.0.0.0|SavisionCommunityMonitorQueryResult.ThreeStateUnitMonitor.623b0f74d7e349e78c0b81d18f914941|| with message:
Failed to verify UnitMonitor: SavisionCommunityMonitorQueryResult.ThreeStateUnitMonitor.623b0f74d7e349e78c0b81d18f914941
: Cannot find ManagementPackElement [Type=ManagementPackUnitMonitorType, ID=SavisionCommunityMonitorQueryResult.ThreeStateConsecutive.UnitMonitorType] in management pack ManagementPack:[Name=SQL.Monitoring, KeyToken=, Version=1.0.0.0].

-------------------------------------------------------

If you you give me any tips on his to fix this it would be great.

Thanks in advance.

Rob

**Comment by UretzkyZvi** [comment]
Hey Rob, 
This is a typical SCOM error, try to follow those blogs: http://thoughtsonopsmgr.blogspot.com/2014/12/error-when-trying-to-remove-web.html
https://www.catapultsystems.com/blogs/removing-obsolete-references-in-custom-management-packs-step-by-step/
