### ISSUE TITLE
SQL Auth test button doesnt work

### ISSUE THREAD

**Issue by snazy2000** [UretzkyZvi/Monitor-Applications-Using-SQL-Queries#3]
![image](https://user-images.githubusercontent.com/1378836/30633404-69467c78-9de3-11e7-9120-d28bc4ae32cd.png)

************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at System.Runtime.InteropServices.Marshal.SecureStringToGlobalAllocUnicode(SecureString s)
   at ManageQueryOleDbMonitorUI.ConnectionAndQuery.convertToUNSecureString(SecureString secstrPassword)
   at ManageQueryOleDbMonitorUI.ConnectionAndQuery.btnTest_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by UretzkyZvi** [comment]
I'm sorry, I totally forget to mention, when you select the SQL Auth option the Test button suppose to be not enabled. The reason is that I can't use SCOM user authentication for any application except SCOM itself. And my test is not SCOM test it a simple C# code, that get as parameter  sql connection string and create command to connect sql. So actually, this test you did is a bug and I will solve it. If you complete the wizard it should works

**Comment by snazy2000** [comment]
When i submit the form i get 
![image](https://user-images.githubusercontent.com/1378836/30685478-ef22490c-9eac-11e7-9fcb-daaece285041.png)

I could not get any extra information as nothing could be clicked on that screen

**Comment by snazy2000** [comment]
I have tried this on both our SQL 2014 cluster and a single server running SQL 2012 both of which error the same :(

**Comment by UretzkyZvi** [comment]
Currently in vacation, I will review the issue on Monday. Thanks:+1:

**Comment by UretzkyZvi** [comment]
Currently in vacation, I will review the issue on Monday. Thanks:+1:

**Comment by UretzkyZvi** [comment]
Hi, 
I am can not find any problem in the template. Is it exist event if you try to create monitor based Windows Authentication?

**Comment by snazy2000** [comment]
Hi
Sorry for not getting back to you sooner !

I have just tested windows auth and I am getting the same error, I was able to run the command using the "Test" button and that worked as expected

Thanks

Stephen.



Date: 17/10/2017 13:21:14
Application: Operations Manager
Application Version: 7.1.10226.1304
Severity: Error
Message: 

: Processing the template failed. See inner exception for details.
Verification failed with 2 errors:
-------------------------------------------------------
Error 1:
Found error in 1|DI.Overrides.and.groups|1.0.0.0|QueryOleDbMonitorInitialDiscovery.3eaa30400f8644aab5a497131c5e353f|| with message:
Failed to verify Discovery: QueryOleDbMonitorInitialDiscovery.3eaa30400f8644aab5a497131c5e353f
: Cannot find ManagementPackElement [Type=ManagementPackClass, ID=Microsoft.Windows.Computer] in management pack ManagementPack:[Name=Microsoft.Windows.Server.2008.Discovery, KeyToken=31bf3856ad364e35, Version=6.0.7323.0].

-------------------------------------------------------
Error 2:
Found error in 1|DI.Overrides.and.groups|1.0.0.0|QueryOleDbMonitorInitialDiscovery.3eaa30400f8644aab5a497131c5e353f/DS|| with message:
The configuration specified for Module DS is not valid.
: Cannot find specified MPElement Windows!Microsoft.Windows.Computer in expression: $MPElement[Name="Windows!Microsoft.Windows.Computer"]/PrincipalName$
Cannot find ManagementPackElement [Type=ManagementPackElement, ID=Microsoft.Windows.Computer] in management pack ManagementPack:[Name=Microsoft.Windows.Server.2008.Discovery, KeyToken=31bf3856ad364e35, Version=6.0.7323.0].
-------------------------------------------------------
Failed to verify Discovery: QueryOleDbMonitorInitialDiscovery.3eaa30400f8644aab5a497131c5e353fCannot find ManagementPackElement [Type=ManagementPackClass, ID=Microsoft.Windows.Computer] in management pack ManagementPack:[Name=Microsoft.Windows.Server.2008.Discovery, KeyToken=31bf3856ad364e35, Version=6.0.7323.0].
: Verification failed with 2 errors:
-------------------------------------------------------
Error 1:
Found error in 1|DI.Overrides.and.groups|1.0.0.0|QueryOleDbMonitorInitialDiscovery.3eaa30400f8644aab5a497131c5e353f|| with message:
Failed to verify Discovery: QueryOleDbMonitorInitialDiscovery.3eaa30400f8644aab5a497131c5e353f
: Cannot find ManagementPackElement [Type=ManagementPackClass, ID=Microsoft.Windows.Computer] in management pack ManagementPack:[Name=Microsoft.Windows.Server.2008.Discovery, KeyToken=31bf3856ad364e35, Version=6.0.7323.0].

-------------------------------------------------------
Error 2:
Found error in 1|DI.Overrides.and.groups|1.0.0.0|QueryOleDbMonitorInitialDiscovery.3eaa30400f8644aab5a497131c5e353f/DS|| with message:
The configuration specified for Module DS is not valid.
: Cannot find specified MPElement Windows!Microsoft.Windows.Computer in expression: $MPElement[Name="Windows!Microsoft.Windows.Computer"]/PrincipalName$
Cannot find ManagementPackElement [Type=ManagementPackElement, ID=Microsoft.Windows.Computer] in management pack ManagementPack:[Name=Microsoft.Windows.Server.2008.Discovery, KeyToken=31bf3856ad364e35, Version=6.0.7323.0].
-------------------------------------------------------


: Failed to verify Discovery: QueryOleDbMonitorInitialDiscovery.3eaa30400f8644aab5a497131c5e353f

: Cannot find ManagementPackElement [Type=ManagementPackClass, ID=Microsoft.Windows.Computer] in management pack ManagementPack:[Name=Microsoft.Windows.Server.2008.Discovery, KeyToken=31bf3856ad364e35, Version=6.0.7323.0].

**Comment by UretzkyZvi** [comment]
Hey,
Could you check in your environment if the Microsoft.Windows.Library MP is minimum version 7.5.8501.0

If not you should update the MP. In case it is a problem, you can fork the project. open it visual studio > replace the Microsoft.Windows.Library with your current version recompile the project and
import the mpb file

**Comment by snazy2000** [comment]
Hey

It has the correct version installed

Stephen

**Comment by UretzkyZvi** [comment]
I have changed the way that I was referencing MPs.

instead of this:
ManagementPack mp = ManagementGroup.ManagementPacks.GetManagementPack(SystemManagementPack.Windows);
                DestinationManagementPack.References.Add("Windows", mp);

I use this:

ManagementPackCriteria mpCriteria = new ManagementPackCriteria("Name='Microsoft.Windows.Library'");
                IList<ManagementPack> managementPacks =
                 ManagementGroup.ManagementPacks.GetManagementPacks(mpCriteria);
                DestinationManagementPack.References.Add("Windows", managementPacks[0]);
                mpCriteria = null;

this way I'm referencing the necessary  "Microsoft.Windows.Library" MP and not counting on "SystemManagementPack.Windows" enumeration...

I hope it will fix the problem.

Thanks for your feedback!

**Comment by snazy2000** [comment]
Have just updated and I get this error (Believe its the same)

https://pastebin.com/PWvNxd6f

**Comment by snazy2000** [comment]
Im not sure why it would be using - Microsoft.Windows.Server.2008.Discovery when the the server running SQL is on Server 2012 R2 with SQL 2014, the SCOM server is also Server 2012 R2

**Comment by UretzkyZvi** [comment]
My environment is the same.. very strange... later today I will check again, maybe I'm missing something.. anyway, if won't find anything, can I connect to your environment remotely?

**Comment by snazy2000** [comment]
I have just tried creating a new MP to store the config and I now get the following error

Note:  The following information was gathered when the operation was attempted.  The information may appear cryptic but provides context for the error.  The application will continue to run.

: Processing the template failed. See inner exception for details.
Cannot resolve identifier Health!System.Health.PerformanceState in the context of management pack SQL.Monitoring. Unknown alias: Health
: Cannot resolve identifier Health!System.Health.PerformanceState in the context of management pack SQL.Monitoring. Unknown alias: Health

Believe this is the same as #4 im running version 2.0.0.5

**Comment by snazy2000** [comment]
We have lift off!! 

I used this powershell script to manually add the 3 dependencies to the MP and it works now

https://blog.tyang.org/2014/10/07/powershell-script-add-mp-references-unsealed-management-packs/

Thanks

**Comment by UretzkyZvi** [comment]
great!!!, however, still I don't understand why you need to add these MPs..
