### ISSUE TITLE
Unable to add monitors to MP that doesn't already contain a reference to the System Health Library MP.

### ISSUE THREAD

**Issue by shadeon** [UretzkyZvi/Monitor-Applications-Using-SQL-Queries#4]
When creating a new monitor, if I select an MP that does not already have a reference to the System Health Library MP the console throws an exception when clicking create on the final step of the wizard and does not save:

Error below:

Processing the template failed. See inner exception for details.
Cannot resolve identifier Health!System.Health.EntityState in the context of management pack Application.MyApp. Unknown alias: Health

**Comment by UretzkyZvi** [comment]
Thanks, 
In the template mp, I forgot to replace hard-coded allies "Health" to $Reference/Health$
I will publish the updated mp very soon.

**Comment by UretzkyZvi** [comment]
Import updated MPs [Link](https://github.com/UretzkyZvi/Monitor-Applications-Using-SQL-Queries/tree/master/ManagementPacks)

Thanks

**Comment by shadeon** [comment]
Nice, thanks for the fast turnaround 👍
