### ISSUE TITLE
Cannot edit the connection and query settings 

### ISSUE THREAD

**Issue by snazy2000** [UretzkyZvi/Monitor-Applications-Using-SQL-Queries#5]
Everything is greyed out apart from browse button, when you go to select new server it then allows you to edit the sql type but everything is still disabled, would be nice to be able to edit the query at least

It is also not showing all the information that was entered when setting up like windows auth tick box etc

Sample interval also turns in to seconds instead of minutes that was selected

**Comment by UretzkyZvi** [comment]
yep I will change it..:+1:

**Comment by UretzkyZvi** [comment]
Done :)
you can check that. The biggest change in this version is the test function, now the test executes the query with default scom agent permission.
