### ISSUE TITLE
Were does the query run from?

### ISSUE THREAD

**Issue by snazy2000** [UretzkyZvi/Monitor-Applications-Using-SQL-Queries#6]
Can you advise which machine performs the query ?

We have had a number of 

Alert description: The agent was not able to submit data on behalf of another computer because agent proxy is not enabled. Details:Health service ( MACHINENAME ) should not generate data about this managed object ( OleDBQueryMonitoringGroup ).

Most machines have this enabled but not all of them, does this mean that every machine is going to be running the same query??

**Comment by UretzkyZvi** [comment]
The machine that host the SQL instance will run the query..By default the monitor configure to be able report remotely, since SQL machine can be virtual in cluster..

**Comment by snazy2000** [comment]
Should the MP be trying to submit data on nodes that are not the SQL cluster then?

**Comment by UretzkyZvi** [comment]
From my perspective, the best way is to execute the query locally from the same machine where the DB engine located. In some scenarios, the DB engine host server is actually a virtual principal name but not necessary, therefore I use a remote able monitor.

**Comment by UretzkyZvi** [comment]
I am closing the issue. feel free to reopen it, 
Thanks again
