### ISSUE TITLE
New managementpacks

### ISSUE THREAD

**Issue by jannepn** [UretzkyZvi/Monitor-Applications-Using-SQL-Queries#8]
Not an issue but a tip.
Here are some tips for management packs that are missing from the database.

ID: Eaton.UPS.Monitoring
Name: Eaton UPS Monitoring
1.0.1.15
https://powerquality.eaton.com/Products-services/Power-Management/Software-Drivers/MS-SCOM-Management-Pack.asp

ID: DataCore.SANsymphonyV.Library
Name: DataCore SANsymphony-V Library
1.3.0.13123
https://www.datacore.com/solutions/by-virtualization-platform/Microsoft/system-center-monitoring-pack.aspx
Need license for the product

HewlettPackard.ProLiant.Monitored.Library
Hewlett-Packard ProLiant Monitored Library Management Pack
3.1.0.0
HewlettPackard.Servers.Library
Hewlett-Packard Servers Core Library
2.3.0.0
https://h20392.www2.hpe.com/portal/swdepot/displayProductInfo.do?productNumber=HPSCOMMP-P
Product #: 
HPSCOMMP-P
Global Trade ID: 
Z7550-63218
Version: 
1.80
Software specification:
HPE ProLiant Management Pack for System Center Operations Manager (Z7550-01351.exe) 
HPE BladeSystem Management Pack for Microsoft System Center Operations Manager (Z7550-01573.exe) 

HPEnterpriseStorageLibraryMP
HPE Storage Library Management Pack for System Center
4.5.0.0
https://h20392.www2.hpe.com/portal/swdepot/displayProductInfo.do?productNumber=System_Center

**Comment by UretzkyZvi** [comment]
Hi @jannepn ,

I believe you meant to update my Nathan Foreman. He created the MPCatalog for SCOM Community MPs.

[MPCatalog link](https://github.com/MPCatalog/scom-community-catalog)
